/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { ConvertLibContract } from "./ConvertLib";
import { ElectionContract } from "./Election";
import { ElectionV2Contract } from "./ElectionV2";
import { MetaCoinContract } from "./MetaCoin";
import { MigrationsContract } from "./Migrations";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(name: "ConvertLib"): ConvertLibContract;
      require(name: "Election"): ElectionContract;
      require(name: "ElectionV2"): ElectionV2Contract;
      require(name: "MetaCoin"): MetaCoinContract;
      require(name: "Migrations"): MigrationsContract;
    }
  }
}

export { ConvertLibContract, ConvertLibInstance } from "./ConvertLib";
export { ElectionContract, ElectionInstance } from "./Election";
export { ElectionV2Contract, ElectionV2Instance } from "./ElectionV2";
export { MetaCoinContract, MetaCoinInstance } from "./MetaCoin";
export { MigrationsContract, MigrationsInstance } from "./Migrations";
